<?php

/**
 * @file
 * Previewable Email Template module.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\pet\Utility\PetHelper;

/**
 * Implements hook_hook_info().
 */
function pet_hook_info() {
  $hooks = ['pet_substitutions_alter'];
  $info = [
    'group' => 'pet',
  ];
  return array_fill_keys($hooks, $info);
}

/**
 * Implements hook_mail().
 *
 * To customize, e.g. to change the content type to text/html etc,
 * you can use hook_mail_alter() in one of your modules.
 *
 * @see https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_mail/8.3.x
 * @see https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_mail_alter/8.3.x
 */
function pet_mail($key, &$message, $params) {

  /** @var \Drupal\pet\Entity\Pet $pet */
  $pet = $params['pet'];
  $context = $params['context'];

  $substitutions = PetHelper::getSubstitutions($context);
  $token = \Drupal::token();

  if ($cc = $pet->getCc()) {
    $message['headers']['Cc'] = $cc;
  }

  if ($bcc = $pet->getBcc()) {
    $message['headers']['Bcc'] = $bcc;
  }

  $message['subject'] = $token->replace($pet->getSubject(), $substitutions, ['clear' => TRUE]);
  $message['body'][] = $token->replace($pet->getBody(), $substitutions, ['clear' => TRUE]);

  // For mimemail module: alternate text-only form for multipart MIME.
  // @todo: mimemail integration.
  /*$mail_body_plain = trim($pet->getBodyPlain());
  if ($mail_body_plain) {
    $message['plaintext'] = $token->replace($mail_body_plain, $substitutions, ['clear' => TRUE]);
  }
  // For mimemail module: send ONLY plain text.
  //$message['plain'] = $pet->getSendPlain();
  */
}

/*
 * Helper functions.
 */

/**
 * Token help for template construction form and template use form.
 */
function pet_token_help() {
  if (\Drupal::moduleHandler()->moduleExists('token')) {
    $tokens = [
      '#title' => new TranslatableMarkup('Replacement patterns'),
      '#type' => 'details',
      '#open' => TRUE,
      '#description' => new TranslatableMarkup('Make sure that the tokens you choose are available to your template when previewed. The list below includes the standard Nodes and Users, as well as global tokens.'),
    ];
    $tokens['token_tree'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => ['node', 'user'],
    ];
  }
  else {
    $tokens = [
      '#markup' => '<p>' . new TranslatableMarkup('Enable the <a href="@drupal-token">Token module</a> to view the available token browser.', ['@drupal-token' => 'http://drupal.org/project/token']) . '</p>',
    ];
  }
  return $tokens;
}
